# -*- coding: utf-8 -*-
"""PURPLE_BLOCK.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1HtJ08V6Sib3WTtx8PuknZD3eaiDQg3-j
"""

def trade(prices):
    buy_price = min(prices)
    sell_price = max(prices[prices.index(buy_price):])
    return buy_price, sell_price

prices = [5, 2, 1, 6, 9, 7]
buy, sell = trade(prices)
print(trade(prices))
print("Best Buy Price:", buy)
print("Best Sell Price:", sell)